# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browserTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1068, 800)
        MainWindow.setStyleSheet("background-color: rgb(245, 244, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tBtn_back = QtWidgets.QToolButton(self.centralwidget)
        self.tBtn_back.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_back.setMaximumSize(QtCore.QSize(45, 30))
        self.tBtn_back.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(158, 158, 158);\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(255, 82, 105);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tBtn_back.setIcon(icon)
        self.tBtn_back.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_back.setObjectName("tBtn_back")
        self.gridLayout.addWidget(self.tBtn_back, 0, 0, 1, 1)
        self.tBtn_reload = QtWidgets.QToolButton(self.centralwidget)
        self.tBtn_reload.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_reload.setMaximumSize(QtCore.QSize(45, 30))
        self.tBtn_reload.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(158, 158, 158);\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(255, 82, 105);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tBtn_reload.setIcon(icon1)
        self.tBtn_reload.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_reload.setObjectName("tBtn_reload")
        self.gridLayout.addWidget(self.tBtn_reload, 0, 1, 1, 1)
        self.tBtn_home = QtWidgets.QToolButton(self.centralwidget)
        self.tBtn_home.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_home.setMaximumSize(QtCore.QSize(45, 30))
        self.tBtn_home.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(158, 158, 158);\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(255, 82, 105);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tBtn_home.setIcon(icon2)
        self.tBtn_home.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_home.setObjectName("tBtn_home")
        self.gridLayout.addWidget(self.tBtn_home, 0, 2, 1, 1)
        self.lE_searchLine = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lE_searchLine.setFont(font)
        self.lE_searchLine.setStyleSheet("QLineEdit {\n"
"    border-radius: 15px;\n"
"    border: 1px solid black;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid black;\n"
"    background-color:  rgb(229, 229, 229);\n"
"}\n"
"")
        self.lE_searchLine.setClearButtonEnabled(True)
        self.lE_searchLine.setObjectName("lE_searchLine")
        self.gridLayout.addWidget(self.lE_searchLine, 0, 3, 1, 1)
        self.tBtn_search = QtWidgets.QToolButton(self.centralwidget)
        self.tBtn_search.setMinimumSize(QtCore.QSize(60, 30))
        self.tBtn_search.setMaximumSize(QtCore.QSize(60, 30))
        self.tBtn_search.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(158, 158, 158);\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(255, 82, 105);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tBtn_search.setIcon(icon3)
        self.tBtn_search.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_search.setObjectName("tBtn_search")
        self.gridLayout.addWidget(self.tBtn_search, 0, 4, 1, 1)
        self.tBtn_changeTheme = QtWidgets.QToolButton(self.centralwidget)
        self.tBtn_changeTheme.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_changeTheme.setMaximumSize(QtCore.QSize(45, 30))
        self.tBtn_changeTheme.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(158, 158, 158);\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(255, 82, 105);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/change_themes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tBtn_changeTheme.setIcon(icon4)
        self.tBtn_changeTheme.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_changeTheme.setObjectName("tBtn_changeTheme")
        self.gridLayout.addWidget(self.tBtn_changeTheme, 0, 5, 1, 1)
        self.tBtn_minimaze = QtWidgets.QToolButton(self.centralwidget)
        self.tBtn_minimaze.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_minimaze.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_minimaze.setFont(font)
        self.tBtn_minimaze.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_minimaze.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_minimaze.setObjectName("tBtn_minimaze")
        self.gridLayout.addWidget(self.tBtn_minimaze, 0, 6, 1, 1)
        self.tBtn_openCloseFullWindow = QtWidgets.QToolButton(self.centralwidget)
        self.tBtn_openCloseFullWindow.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_openCloseFullWindow.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.tBtn_openCloseFullWindow.setFont(font)
        self.tBtn_openCloseFullWindow.setAutoFillBackground(False)
        self.tBtn_openCloseFullWindow.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_openCloseFullWindow.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_openCloseFullWindow.setObjectName("tBtn_openCloseFullWindow")
        self.gridLayout.addWidget(self.tBtn_openCloseFullWindow, 0, 7, 1, 1)
        self.tBtn_closeWindow = QtWidgets.QToolButton(self.centralwidget)
        self.tBtn_closeWindow.setMinimumSize(QtCore.QSize(45, 30))
        self.tBtn_closeWindow.setMaximumSize(QtCore.QSize(45, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tBtn_closeWindow.setFont(font)
        self.tBtn_closeWindow.setStyleSheet("QToolButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"    background-color: rgb(213, 63, 91);\n"
"    color: white;\n"
"}\n"
"QToolButton:hover {\n"
"    border: 2px solid black;\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"QToolButton:pressed {\n"
"    border: 2px solid black;\n"
"    color: white;\n"
"    background-color: rgb(184, 21, 32);\n"
"}")
        self.tBtn_closeWindow.setIconSize(QtCore.QSize(20, 20))
        self.tBtn_closeWindow.setObjectName("tBtn_closeWindow")
        self.gridLayout.addWidget(self.tBtn_closeWindow, 0, 8, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("border: 1px solid black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 9)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Браузер"))
        self.tBtn_back.setText(_translate("MainWindow", "..."))
        self.tBtn_reload.setText(_translate("MainWindow", "..."))
        self.tBtn_home.setText(_translate("MainWindow", "..."))
        self.lE_searchLine.setPlaceholderText(_translate("MainWindow", "https://"))
        self.tBtn_search.setText(_translate("MainWindow", "..."))
        self.tBtn_changeTheme.setText(_translate("MainWindow", "..."))
        self.tBtn_minimaze.setText(_translate("MainWindow", "_"))
        self.tBtn_openCloseFullWindow.setText(_translate("MainWindow", "□"))
        self.tBtn_closeWindow.setText(_translate("MainWindow", "X"))
import res_rc
