# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browser_auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 100)
        Form.setMinimumSize(QtCore.QSize(300, 100))
        Form.setMaximumSize(QtCore.QSize(300, 100))
        Form.setStyleSheet("background-color: rgb(245, 244, 255);")
        self.lE_enterPassword = QtWidgets.QLineEdit(Form)
        self.lE_enterPassword.setGeometry(QtCore.QRect(10, 10, 280, 31))
        self.lE_enterPassword.setStyleSheet("QLineEdit {\n"
"    border-radius: 15px;\n"
"    border: 1px solid black;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid black;\n"
"    background-color:  rgb(229, 229, 229);\n"
"}\n"
"")
        self.lE_enterPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lE_enterPassword.setObjectName("lE_enterPassword")
        self.btn_enter = QtWidgets.QPushButton(Form)
        self.btn_enter.setGeometry(QtCore.QRect(85, 50, 130, 40))
        self.btn_enter.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButtonn:hover {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(158, 158, 158);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 2px solid black;\n"
"    background-color: rgb(255, 82, 105);\n"
"}")
        self.btn_enter.setObjectName("btn_enter")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lE_enterPassword.setPlaceholderText(_translate("Form", "Введите пароль:"))
        self.btn_enter.setText(_translate("Form", "Войти"))
